# https://taskfile.dev

version: "3"

vars:
  MSG: Default Commit Message
  BRANCH: test-branch

tasks:
  default:
    desc: Default task = show tasks
    cmds:
      - task -a
    silent: true

  init-py:
    desc: Add key python packages to environment
    cmds:
      - uv pip compile requirements.in -o requirements.txt
      #- uv add -r requirements.in -c requirements.txt
      - sleep 0.33
      - uv add -r requirements.txt

  run-main:
    desc: Run the root directory main.py installed by uv
    cmds:
      - uv run main.py

  do-cli:
    desc: Run the cli.py installed by uv
    cmds:
      - uv run python3 -m cli

  elixir-orchestrate:
    desc: Run elixir orchestrator
    cmds:
      - cd orchestrate && mix clean && mix deps.get && mix compile

  add-bin:
    desc: Add a rust binary to execute workspace
    cmds:
      - cargo install --path .

  elixir-interactive:
    desc: Run elixir interactive repl
    cmds:
      - cd orchestrate && iex -S mix

  test-nifs:
    desc: Run cargo nif_actions tests
    cmds:
      - cd execute && cargo test

  # [] TODO: consider using scripts to simplify other commands
  git:
    desc: Run git python script
    cmds:
      - uv run python3 -m src.git.git

  run-csv:
    desc: Run elixir csv example
    cmds:
      - cd orchestrate && mix deps.get && mix compile

  archive:
    desc: Backup using tar & zst
    cmds:
      - echo "Archiving directories"
      - git-lfs track "*.zst"

  profile-csv:
    desc: Profile csv files
    cmds:
      - uv run python3 -m scripts.profiling.profiler

  run:
    desc: Run src app
    cmds:
      - uv run python3 -m src.menu
