# https://taskfile.dev

version: '3'

vars:
  MSG: Default Commit Message
  BRANCH: test-branch

tasks:
  default:
    desc: Default task = show tasks
    cmds:
      - task -a
    silent: true

  init-py:
    desc: Add key python packages to environment
    cmds:
      - uv pip compile requirements.in -o requirements.txt
      #- uv add -r requirements.in -c requirements.txt
      - sleep 0.33
      - uv add -r requirements.txt

  run-main:
    desc: Run the root directory main.py installed by uv
    cmds:
      - uv run main.py

  do-cli:
    desc: Run the cli.py installed by uv
    cmds:
      - uv run python3 -m cli

  elixir-orchestrate:
    desc: Run elixir orchestrator
    cmds:
      - cd orchestrate && mix clean && mix deps.get && mix compile

  add-bin:
    desc: Add a rust binary to execute workspace
    cmds:
      - cargo install --path .

  elixir-interactive:
    desc: Run elixir interactive repl
    cmds:
      - cd orchestrate && iex -S mix

  test-nifs:
    desc: Run cargo nif_actions tests
    cmds:
      - cd execute && cargo test

  git-stat:
    desc: Run git commands
    cmds:
      - git status

  git-push:
    desc: Update repo
    cmds:
      - git add .
      - git commit -m "{{.MSG}}"
      - git push

  new-branch:
    desc: Create a new branch
    cmds:
      - git checkout -b {{.BRANCH}}
      - git push --set-upstream origin {{.BRANCH}}

  merge:
    desc: Merge a branch
    cmds:
      - git switch main
      - git merge {{.BRANCH}}
      - git push

  ls-branches:
    desc: List branches
    cmds:
      - git branch -v

  ls-branches-all:
    desc: List all branches
    cmds:
      - git branch -a
